-- Script para ACTUALIZAR el contenido de términos si ya existe la tabla
-- Ejecuta este script si ya tienes la tabla creada pero necesitas actualizar el contenido

-- Primero, eliminar registros existentes (opcional, solo si quieres empezar de cero)
DELETE FROM `terminos_condiciones`;

-- Insertar el nuevo contenido
INSERT INTO `terminos_condiciones` (`version`, `contenido_html`, `estado_activo`) 
VALUES ('1.0', '<h1>Términos y Condiciones de Uso</h1><h2>1. Aceptación de los Términos</h2><p>Al utilizar esta aplicación de registro de asistencia, usted acepta expresamente estos términos y condiciones en su totalidad. Si no está de acuerdo con estos términos, no debe utilizar esta aplicación.</p><h2>2. Uso de Datos Biométricos</h2><p>Nuestra aplicación utiliza tecnología de reconocimiento facial para verificar su identidad durante el registro de asistencia. Al aceptar estos términos, usted autoriza expresamente:</p><ul><li>La captura de fotografías de su rostro durante cada registro de entrada y salida</li><li>El procesamiento de sus datos biométricos faciales para verificación de identidad</li><li>El almacenamiento seguro de estas imágenes en nuestros servidores</li><li>El uso de algoritmos de comparación facial para validar su identidad</li></ul><h2>3. Uso de Datos de Geolocalización</h2><p>La aplicación requiere acceso a su ubicación GPS para:</p><ul><li>Verificar que se encuentra en el lugar de trabajo autorizado</li><li>Registrar la ubicación exacta de cada entrada y salida</li><li>Generar reportes de asistencia con información geográfica</li><li>Validar el cumplimiento de políticas de trabajo remoto o presencial</li></ul><h2>4. Privacidad y Seguridad de Datos</h2><p>Nos comprometemos a:</p><ul><li>Proteger sus datos personales y biométricos con medidas de seguridad apropiadas</li><li>No compartir sus datos con terceros sin su consentimiento expreso</li><li>Utilizar sus datos únicamente para fines de control de asistencia laboral</li><li>Cumplir con todas las regulaciones de protección de datos aplicables</li></ul><h2>5. Derechos del Usuario</h2><p>Usted tiene derecho a:</p><ul><li>Acceder a sus datos personales almacenados</li><li>Solicitar la corrección de datos inexactos</li><li>Solicitar la eliminación de sus datos (sujeto a obligaciones legales de retención)</li><li>Revocar su consentimiento en cualquier momento</li></ul><h2>6. Uso Aceptable</h2><p>Usted se compromete a:</p><ul><li>Utilizar la aplicación únicamente para registrar su propia asistencia</li><li>No intentar suplantar la identidad de otros usuarios</li><li>No manipular o falsificar datos de ubicación</li><li>Reportar cualquier problema técnico o de seguridad detectado</li></ul><h2>7. Modificaciones</h2><p>Nos reservamos el derecho de modificar estos términos en cualquier momento. Los cambios entrarán en vigor inmediatamente después de su publicación en la aplicación.</p><h2>8. Contacto</h2><p>Para cualquier consulta sobre estos términos o sobre el tratamiento de sus datos, puede contactarnos a través de los canales oficiales de la empresa.</p><p><strong>Última actualización:</strong> Diciembre 2025</p>', 1);
